(()=>{
const generated=window.ClippingHQGeneratedVideos=new Map(),urls=new Map(),$=s=>document.querySelector(s);
const key=i=>queue?.[i]?.url||`item-${i}`,get=i=>generated.get(key(i));
const clean=s=>String(s||'').replace(/\((?:visual|on.?screen|b-roll|show)[^)]*\)/gi,' ').replace(/\[(?:visual|on.?screen|b-roll|show)[^\]]*\]/gi,' ').replace(/\s+/g,' ').trim();
const source=x=>{try{return new URL(x?.url||'').hostname.replace(/^www\./,'')}catch{return'source lead'}};
function phrases(s){const out=[];for(const p of(s.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[s])){const w=p.trim().split(/\s+/);for(let i=0;i<w.length;i+=10)out.push(w.slice(i,i+10).join(' '))}return out.filter(Boolean)}
function phraseAt(a,p){if(!a.length)return'';return a[Math.min(a.length-1,Math.floor(p*a.length))]}
function lines(ctx,s,width,max=7){const out=[];let line='';for(const word of String(s).split(/\s+/)){const next=line?`${line} ${word}`:word;if(line&&ctx.measureText(next).width>width){out.push(line);line=word;if(out.length===max-1)break}else line=next}if(line&&out.length<max)out.push(line);return out}
function rr(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}
function cover(c,m,w,h,zoom=1){const mw=m.videoWidth||m.naturalWidth,mh=m.videoHeight||m.naturalHeight;if(!mw||!mh)return false;const sc=Math.max(w/mw,h/mh)*zoom,sw=w/sc,sh=h/sc;c.drawImage(m,(mw-sw)/2,(mh-sh)/2,sw,sh,0,0,w,h);return true}
function fallback(c,w,h,t){const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,'#060814');g.addColorStop(.5,'#24104b');g.addColorStop(1,'#05333b');c.fillStyle=g;c.fillRect(0,0,w,h);for(let n=0;n<5;n++){const x=w*(.12+.2*n)+Math.sin(t+n)*60,y=h*(.12+.18*n)+Math.cos(t*.7+n)*70,r=c.createRadialGradient(x,y,4,x,y,240);r.addColorStop(0,n%2?'#22d3ee55':'#8b5cf666');r.addColorStop(1,'#0000');c.fillStyle=r;c.fillRect(0,0,w,h)}}
function draw(c,cv,item,parts,p,asset){const w=cv.width,h=cv.height,t=performance.now()/1000;let ok=false;try{if(asset)ok=cover(c,asset.el,w,h,asset.kind==='image'?1.08+.05*Math.sin(p*Math.PI):1)}catch{}if(!ok)fallback(c,w,h,t);c.fillStyle='#03050c55';c.fillRect(0,0,w,h);const sh=c.createLinearGradient(0,0,0,h);sh.addColorStop(0,'#050710dd');sh.addColorStop(.42,'#05071015');sh.addColorStop(1,'#050710ee');c.fillStyle=sh;c.fillRect(0,0,w,h);c.fillStyle='#080b14cc';rr(c,38,38,w-76,68,23);c.fill();c.fillStyle='#c4b5fd';c.font='800 23px Inter,Arial';c.fillText('CLIPPING HQ',64,81);c.textAlign='right';c.fillStyle='#73f0c1';c.font='700 17px Inter,Arial';c.fillText('ORIGINAL COMMENTARY',w-62,80);c.textAlign='left';c.fillStyle='#fff';c.font='800 42px Inter,Arial';let y=160;for(const l of lines(c,item.title||"Today's story",w-96,4)){c.fillText(l,48,y);y+=51}c.font='800 48px Inter,Arial';const cap=lines(c,phraseAt(parts,p),w-112,6),bh=Math.max(178,cap.length*61+65),by=Math.min(h-330,Math.max(650,h*.63-bh/2));c.fillStyle='#050810dd';rr(c,34,by,w-68,bh,28);c.fill();c.strokeStyle='#c4b5fd88';c.lineWidth=3;c.stroke();c.fillStyle='#fff';y=by+62;for(const l of cap){c.fillText(l,55,y);y+=61}c.fillStyle='#cbd5e1';c.font='700 17px Inter,Arial';c.fillText(`SOURCE LEAD: ${source(item)}`.toUpperCase(),45,h-112);c.fillStyle='#ffffff33';rr(c,45,h-75,w-90,11,6);c.fill();c.fillStyle='#8b5cf6';rr(c,45,h-75,(w-90)*p,11,6);c.fill();c.fillStyle='#a3adc2';c.font='600 15px Inter,Arial';c.fillText('Context • narration • licensed visuals',45,h-35)}
async function requestAssets(item,script){try{const r=await apiFetch('/api/video/narration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'assets',title:item.title,script})});return r.ok?await r.json():{assets:[]}}catch{return{assets:[]}}}
function loadAsset(a){return new Promise(resolve=>{let done=false;const finish=x=>{if(!done){done=true;resolve(x)}};if(a.type==='video'){const el=document.createElement('video');el.crossOrigin='anonymous';el.muted=true;el.loop=true;el.playsInline=true;el.preload='auto';el.onloadeddata=async()=>{try{await el.play()}catch{}finish({el,kind:'video',meta:a})};el.onerror=()=>finish(null);el.src=a.url}else{const el=new Image();el.crossOrigin='anonymous';el.onload=()=>finish({el,kind:'image',meta:a});el.onerror=()=>finish(null);el.src=a.url}setTimeout(()=>finish(null),10000)})}
async function loadAssets(list,progress){const out=[];for(let i=0;i<Math.min(4,list.length);i++){progress.textContent=`Loading licensed visual ${i+1} of ${Math.min(4,list.length)}…`;const a=await loadAsset(list[i]);if(a)out.push(a)}return out}
async function voice(text){const c=new AbortController(),timer=setTimeout(()=>c.abort(),45000);try{const r=await apiFetch('/api/video/narration',{method:'POST',signal:c.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||`Narration failed (${r.status})`)}return r.arrayBuffer()}finally{clearTimeout(timer)}}
async function render(item,audioBuffer,assets,progress){if(!window.MediaRecorder)throw Error('Use current Chrome or Edge to render videos.');const AC=window.AudioContext||window.webkitAudioContext,ac=new AC();await ac.resume();const audio=await ac.decodeAudioData(audioBuffer.slice(0)),cv=document.createElement('canvas');cv.width=720;cv.height=1280;const c=cv.getContext('2d'),parts=phrases(clean(section(item.pack,'SHORT SCRIPT')||item.hook||item.title)),vs=cv.captureStream(30),dest=ac.createMediaStreamDestination(),src=ac.createBufferSource();src.buffer=audio;src.connect(dest);const stream=new MediaStream([...vs.getVideoTracks(),...dest.stream.getAudioTracks()]),types=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'],mime=types.find(x=>MediaRecorder.isTypeSupported(x))||'',rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:3500000,audioBitsPerSecond:128000}:{videoBitsPerSecond:3500000}),chunks=[];rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};let stop=false,raf,start=performance.now();const frame=()=>{const p=Math.min(1,(performance.now()-start)/(audio.duration*1000)),asset=assets.length?assets[Math.min(assets.length-1,Math.floor(p*assets.length))]:null;draw(c,cv,item,parts,p,asset);if(!stop)raf=requestAnimationFrame(frame)};const done=new Promise((ok,bad)=>{rec.onerror=e=>bad(e.error||Error('Video recorder failed'));rec.onstop=()=>ok(new Blob(chunks,{type:mime||'video/webm'}))});rec.start(1000);frame();src.start();progress.textContent=`Rendering ${Math.round(audio.duration)} seconds of animated video… keep this tab open.`;await new Promise(ok=>src.onended=()=>{stop=true;cancelAnimationFrame(raf);setTimeout(()=>{rec.stop();ok()},250)});const blob=await done;vs.getTracks().forEach(x=>x.stop());dest.stream.getTracks().forEach(x=>x.stop());assets.forEach(x=>{if(x.kind==='video'){x.el.pause();x.el.removeAttribute('src')}});await ac.close();return blob}
const modal=document.createElement('div');modal.id='videoMakerModal';modal.className='modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="modal-card publish-card"><div class="modal-head"><div><p class="eyebrow">AI VIDEO MAKER</p><h2>Build a real animated Short</h2><p class="sub">Narration, timed captions, motion design, and licensed online visuals.</p></div><button id="closeVideoMaker" class="icon-btn">×</button></div><div class="publish-form"><div id="videoMakerProgress" class="publish-progress">Ready.</div><div id="videoMakerPreview"></div><div class="notice"><b>Visual sourcing:</b> Uses Pexels when configured, then Wikimedia Commons. Visual credits stay attached to each preview.</div></div><div class="modal-actions"><button id="closeVideoMaker2" class="ghost">Close</button><button id="videoMakerBoth" class="primary" disabled>🚀 Send same video to both</button></div></div>`;document.body.insertBefore(modal,$('#toast'));let active=-1;const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};$('#closeVideoMaker').onclick=close;$('#closeVideoMaker2').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
function buttons(){document.querySelectorAll('#queueList .clip-card').forEach((card,i)=>{const a=card.querySelector('.queue-actions,.clip-actions');if(!a)return;if(!a.querySelector('.make-video')){const b=document.createElement('button');b.className='make-video';b.textContent='🎬 Make Video';b.onclick=()=>make(i);a.insertBefore(b,a.querySelector('.yt-upload'))}if(!a.querySelector('.post-both')){const b=document.createElement('button');b.className='post-both';b.textContent='🚀 Both';b.onclick=()=>post(i);a.insertBefore(b,[...a.querySelectorAll('button')].find(x=>x.textContent.trim()==='Remove')||null)}a.querySelector('.post-both').disabled=!get(i)})}
if($('#queueList'))new MutationObserver(buttons).observe($('#queueList'),{childList:true,subtree:true});
async function make(i){const item=queue[i];if(!item?.pack)return toast('Generate the AI Pack first ✦');active=i;modal.classList.add('open');const p=$('#videoMakerProgress'),view=$('#videoMakerPreview'),both=$('#videoMakerBoth');both.disabled=true;view.innerHTML='';try{let script=clean(section(item.pack,'SHORT SCRIPT')||item.hook||item.title);if(script.split(/\s+/).filter(Boolean).length<20){const expanded=clean([script,item.hook,item.why,item.title].filter(Boolean).join('. '));if(expanded.length>script.length)script=expanded}if(!script)throw Error('No script or story text is available for this item.');p.textContent='Finding relevant licensed visuals…';const data=await requestAssets(item,script),assets=await loadAssets(data.assets||[],p);p.textContent='Creating narration…';const audio=await voice(script),blob=await render(item,audio,assets,p),name=(section(item.pack,'TITLE')||'clipping-hq-video').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,55)||'clipping-hq-video',file=new File([blob],`${name}.webm`,{type:'video/webm'}),k=key(i);generated.set(k,file);if(urls.has(k))URL.revokeObjectURL(urls.get(k));const u=URL.createObjectURL(file);urls.set(k,u);item.videoReady=true;localStorage.setItem('clipQueue',JSON.stringify(queue));const credits=(data.assets||[]).slice(0,4).map((a,n)=>a.sourceUrl?`<a href="${escapeHtml(a.sourceUrl)}" target="_blank" rel="noopener">${escapeHtml(a.provider)} ${n+1}</a>`:escapeHtml(a.provider)).join(' • ');view.innerHTML=`<video controls playsinline src="${u}" style="width:min(320px,100%);aspect-ratio:9/16;display:block;margin:4px auto 14px;border-radius:16px;background:#000"></video><div style="text-align:center;font-size:12px"><a href="${u}" download="${file.name}" style="color:#c4b5fd">Save video ↧</a>${credits?`<div style="margin-top:8px;color:#9aa3b8">Credits: ${credits}</div>`:''}</div>`;p.innerHTML=`Video ready ✓<br><span>${Math.round(file.size/104857.6)/10} MB • 720×1280 • ${assets.length?`${assets.length} online visuals`:'animated motion graphics'}</span>`;both.disabled=false;renderQueue();buttons();toast('Real video ready 🎬')}catch(e){p.textContent='Video maker error: '+(e.message||'Unknown error')}}
window.makeVideo=make;
async function youtube(file,item){const title=(section(item.pack,'TITLE')||item.title||'Clipping HQ Short').slice(0,100),description=(section(item.pack,'CAPTION')||section(item.pack,'SHORT SCRIPT')||item.hook||'').slice(0,5000),r=await apiFetch('/api/youtube/upload-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description,contentType:file.type,contentLength:file.size})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`YouTube session failed (${r.status})`);const up=await fetch(d.uploadUrl,{method:'PUT',headers:{Authorization:`Bearer ${d.accessToken}`,'Content-Type':file.type},body:file}),ud=await up.json().catch(()=>({}));if(!up.ok)throw Error(ud?.error?.message||`YouTube upload failed (${up.status})`);return ud.id}
async function tiktok(file){const r=await apiFetch('/api/tiktok/upload-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentType:file.type,contentLength:file.size})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`TikTok session failed (${r.status})`);const up=await fetch(d.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type,'Content-Range':`bytes 0-${file.size-1}/${file.size}`},body:file});if(!up.ok)throw Error((await up.text().catch(()=>''))||`TikTok upload failed (${up.status})`);return d.publishId}
async function post(i){const item=queue[i],file=get(i);if(!file)return toast('Make the video first 🎬');active=i;modal.classList.add('open');const p=$('#videoMakerProgress'),both=$('#videoMakerBoth');both.disabled=true;p.textContent='Sending the same video to both platforms…';p.scrollIntoView({behavior:'smooth',block:'center'});const [yt,tt]=await Promise.allSettled([youtube(file,item),tiktok(file)]),yo=yt.status==='fulfilled',to=tt.status==='fulfilled';if(yo)item.youtubeVideoId=yt.value;if(to)item.tiktokPublishId=tt.value;localStorage.setItem('clipQueue',JSON.stringify(queue));p.innerHTML=`${escapeHtml(yo?'YouTube: uploaded Private ✓':`YouTube: ${yt.reason?.message||'failed'}`)}<br>${escapeHtml(to?'TikTok: draft transferred ✓':`TikTok: ${tt.reason?.message||'failed'}`)}<br><span>${yo&&to?'Both received the exact same video. Open TikTok notifications to finish its draft.':'The successful platform was preserved; the exact remaining error is above.'}</span>`;p.scrollIntoView({behavior:'smooth',block:'center'});both.disabled=false;toast(yo&&to?'Sent to both ✓':yo?'YouTube uploaded; TikTok needs attention':to?'TikTok transferred; YouTube needs attention':'Both uploads failed')}
window.postBoth=post;$('#videoMakerBoth').onclick=()=>active>=0&&post(active);buttons();
})();
